//RESUME DATA IN JSON FORMAT

let resume=[{"bio_data":
{
    "name": "M.SHANMUGASUNDARAM",
    "E-mail": "abdeshanmugam@gmail.com",
    "mobil": '9925254730',
    "Address": "seelanayakkanpatti, 1062thungavi (Po), madathukulam(Tk), Tiruppur(Dt), 642203"},
},
    { 
        "Career Objective" : "To be an innovator in a team to express my skills in a leading corporate and to update myself with new things that would be benefit of the organization and myself.",
     
    },
     
   
    
    {
     
        "Course" : "MSW",
        "Institute" : "SreeSaraswathiThyagarCollege",
        "University": "Bharathiyar University",
        "Percentage": "71%",
        "YearofPassing": "2019-2021"
     },

        {"Course" : "B.com (CA)",
        "Institute" : "SreeSaraswathiThyagarCollege",
        "University": "Bharathiyar University",
        "Percentage": "60%",
        "YearofPassing": "2016-2019"},

        {"Course": "12",
        "Institute" : "SVHS",
        "University": "State Board",
        "Percentage": "72%",
        "YearofPassing": "2016"},


        {"Course": "10",
        "Institute" : "SVHS",
        "University": "State Board",
        "Percentage": "65%",
        "YearofPassing": "2014" },
       

    

    {
        "Skills": "MS Office , Excel ,Computer skill"
    },
    
    {
        "Personal_Details":{
            "Date of Birth": "07/ Dec / 1998",
            "Nationality" : "Indian"

        },
    },

    {
        "Experience": "Worked as a psychiatric social worker in jeevarakshai de-addiction cum rehabilitation and psychiatric care for 1 year"
    },

    {
        "Declaration": "I hereby the above given details are true to the best of my knowledge."
    }
];






// 2 for , for in , for of ,foreach


//for in

//for(var i in resume){
  //  console.log(resume[i].Education_Qualifications);
//}


// for

 //var N=+resume.length
//for(var j=0; j<N;j=j+1){
   // console.log(resume[j].Education_Qualifications)
//}

//for of

//for(var x of resume){
   // console.log(x["Course"], "   ",x["Institute"]);
//}

//foreach

